/**
 * Single source of truth for wire types: re-export the daemon's own domain
 * types (type-only, erased at build time — nothing from src/ is bundled).
 */
export type {
  CommentAnchor,
  CommentCounts,
  CommentKind,
  CommentReply,
  CommentState,
  CommentTag,
  DiffManifest,
  FeedbackBatch,
  FileContentResult,
  FileDiff,
  FileStatus,
  Hunk,
  HunkLine,
  InterdiffFile,
  InterdiffFileSummary,
  InterdiffManifest,
  LineKind,
  ManifestFile,
  MarkReadyResult,
  RangeSpec,
  ReviewComment,
  RevisionInfo,
  RevisionsResult,
  SearchMatch,
  SearchResult,
  SendFeedbackResult,
  Session,
  SessionState,
  Side,
  SuggestionResult,
} from "../../src/types";
