/**
 * Default collapse rules (spec §7.1): deleted files, generated files
 * (filename pattern + @generated / DO NOT EDIT header check), and any single
 * file above the changed-line threshold. Collapsed files stay in the tree,
 * deemphasized — never hidden (spec §2).
 */

import type { FileDiff, ManifestFile } from "../types";

export const LARGE_FILE_COLLAPSE_LINES = 800;

const GENERATED_BASENAMES: ReadonlySet<string> = new Set([
  "package-lock.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "bun.lock",
  "bun.lockb",
  "composer.lock",
  "gemfile.lock",
  "cargo.lock",
  "poetry.lock",
  "uv.lock",
  "go.sum",
  "flake.lock",
  "packages.lock.json",
]);

const GENERATED_PATTERNS: readonly RegExp[] = [
  /\.min\.(js|css)$/i,
  /\.(js|css)\.map$/i,
  /\.snap$/i,
  /\.pb\.(go|py|rb|cc|h)$/i,
  /_pb2(_grpc)?\.py$/i,
  /\.generated\.[^/]+$/i,
  /(^|\/)__snapshots__\//,
  /(^|\/)node_modules\//,
  /(^|\/)vendor\//,
  /(^|\/)dist\//,
  /(^|\/)build\//,
];

export function isGeneratedPath(path: string): boolean {
  const base = path.slice(path.lastIndexOf("/") + 1).toLowerCase();
  if (GENERATED_BASENAMES.has(base)) return true;
  return GENERATED_PATTERNS.some((re) => re.test(path));
}

/** @generated / DO NOT EDIT header check over the first lines of the diff. */
export function hasGeneratedHeader(diff: FileDiff): boolean {
  let scanned = 0;
  for (const hunk of diff.hunks) {
    for (const line of hunk.lines) {
      if (scanned >= 30) return false;
      scanned++;
      if (/@generated|DO NOT EDIT|Code generated by|autogenerated/i.test(line.text)) return true;
    }
  }
  return false;
}

/** Manifest-level rule (content-independent part of spec §7.1). */
export function defaultCollapsed(file: ManifestFile): boolean {
  if (file.status === "deleted") return true;
  if (isGeneratedPath(file.path)) return true;
  if (file.additions + file.deletions > LARGE_FILE_COLLAPSE_LINES) return true;
  return false;
}
