import { describe, expect, test } from "bun:test";
import type { FileDiff, ManifestFile } from "../types";
import { defaultCollapsed, hasGeneratedHeader, isGeneratedPath } from "./collapse";

const file = (path: string, overrides: Partial<ManifestFile> = {}): ManifestFile => ({
  path,
  status: "modified",
  additions: 10,
  deletions: 5,
  binary: false,
  large: false,
  ...overrides,
});

describe("default collapse rules (§7.1)", () => {
  test("deleted files collapse", () => {
    expect(defaultCollapsed(file("src/app.ts", { status: "deleted" }))).toBe(true);
  });

  test("lockfiles and generated patterns collapse", () => {
    for (const p of [
      "package-lock.json",
      "deps/yarn.lock",
      "bun.lock",
      "Cargo.lock",
      "go.sum",
      "dist/bundle.min.js",
      "app.css.map",
      "tests/__snapshots__/auth.snap",
      "proto/api.pb.go",
      "gen/thing.generated.ts",
    ]) {
      expect(isGeneratedPath(p)).toBe(true);
      expect(defaultCollapsed(file(p))).toBe(true);
    }
  });

  test("ordinary source files stay expanded", () => {
    for (const p of ["src/auth.py", "lib/locks.ts", "README.md", "distributed/map.ts"]) {
      expect(isGeneratedPath(p)).toBe(false);
      expect(defaultCollapsed(file(p))).toBe(false);
    }
  });

  test("files above ~800 changed lines collapse regardless of type", () => {
    expect(defaultCollapsed(file("src/big.ts", { additions: 700, deletions: 200 }))).toBe(true);
    expect(defaultCollapsed(file("src/ok.ts", { additions: 400, deletions: 300 }))).toBe(false);
  });
});

describe("@generated / DO NOT EDIT header detection", () => {
  const diffWith = (texts: string[]): FileDiff => ({
    path: "gen.ts",
    binary: false,
    large: false,
    hunks: [
      {
        old_start: 1,
        old_lines: 0,
        new_start: 1,
        new_lines: texts.length,
        header: "",
        lines: texts.map((text, i) => ({
          kind: "add" as const,
          old_line: null,
          new_line: i + 1,
          text,
        })),
      },
    ],
  });

  test("header markers within the first lines are detected", () => {
    expect(hasGeneratedHeader(diffWith(["// @generated by protoc", "export {}"]))).toBe(true);
    expect(hasGeneratedHeader(diffWith(["/* DO NOT EDIT */"]))).toBe(true);
    expect(hasGeneratedHeader(diffWith(["// Code generated by mockgen."]))).toBe(true);
  });

  test("markers deep in the file are ignored (cheap check only)", () => {
    const lines = Array.from({ length: 40 }, (_, i) => `line ${i}`);
    lines.push("// @generated");
    expect(hasGeneratedHeader(diffWith(lines))).toBe(false);
  });

  test("ordinary files do not match", () => {
    expect(hasGeneratedHeader(diffWith(["import x from 'y';", "export const a = 1;"]))).toBe(
      false,
    );
  });
});
